from .er.er import ER
from .agem.agem import AGEM
from .coral.coral import DeepCORAL
from .erm.erm import ERM
from .ewc.ewc import EWC
from .groupdro.groupdro import GroupDRO
from .irm.irm import IRM
from .lora.lora import LoRA
from .adapter.adapter import Adapter
